extends:
  - spectral:oas

rules:
  # Todos los endpoints deben tener operationId
  operation-operationId: error

  # Todos los endpoints deben tener al menos un tag
  operation-tags: error

  # Parámetros de path deben tener descripción
  parameter-description: warn

  # Las respuestas de error deben existir
  operation-4xx-response: warn
