import { defineConfig } from 'orval';

export default defineConfig({
  love4sneakers: {
    input: {
      target: './docs/openapi/openapi.yaml',
    },
    output: {
      target: './frontend/src/app/core/api/generated/api.ts',
      schemas: './frontend/src/app/core/api/generated/model',
      client: 'angular',
      baseUrl: '',
      override: {
        header: () => [
          'eslint-disable',
          'AUTOGENERATED — DO NOT EDIT',
          'Regenerate with: npm run generate:api',
        ],
      },
    },
  },
});
